version: '3.8'

services:
  backend:
    build:
      context: ../api-back-avancado-puc3
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=sqlite:////app/data/app.db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  sqlite_data:
